# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Space Wave' do
  use_frameworks!

pod 'SDWebImage'
pod 'Appirater'
pod 'Firebase/Analytics'

end
